/*
 * My histories API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {Profile} from './Profile';

/**
 * The History model module.
 * @module model/History
 * @version v1
 */
export class History {
  /**
   * Constructs a new <code>History</code>.
   * @alias module:model/History
   * @class
   * @param body {String} 
   * @param title {String} 
   */
  constructor(body, title) {
    this.body = body;
    this.title = title;
  }

  /**
   * Constructs a <code>History</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/History} obj Optional instance to populate.
   * @return {module:model/History} The populated <code>History</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new History();
      if (data.hasOwnProperty('author'))
        obj.author = Profile.constructFromObject(data['author']);
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'String');
      if (data.hasOwnProperty('description'))
        obj.description = ApiClient.convertToType(data['description'], 'String');
      if (data.hasOwnProperty('favorited'))
        obj.favorited = ApiClient.convertToType(data['favorited'], 'String');
      if (data.hasOwnProperty('favoritesCount'))
        obj.favoritesCount = ApiClient.convertToType(data['favoritesCount'], 'String');
      if (data.hasOwnProperty('slug'))
        obj.slug = ApiClient.convertToType(data['slug'], 'String');
      if (data.hasOwnProperty('tagList'))
        obj.tagList = ApiClient.convertToType(data['tagList'], ['String']);
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'String');
    }
    return obj;
  }
}

/**
 * @member {module:model/Profile} author
 */
History.prototype.author = undefined;

/**
 * @member {String} body
 */
History.prototype.body = undefined;

/**
 * @member {String} createdAt
 */
History.prototype.createdAt = undefined;

/**
 * @member {String} description
 */
History.prototype.description = undefined;

/**
 * @member {String} favorited
 */
History.prototype.favorited = undefined;

/**
 * @member {String} favoritesCount
 */
History.prototype.favoritesCount = undefined;

/**
 * @member {String} slug
 */
History.prototype.slug = undefined;

/**
 * @member {Array.<String>} tagList
 */
History.prototype.tagList = undefined;

/**
 * @member {String} title
 */
History.prototype.title = undefined;

/**
 * @member {String} updatedAt
 */
History.prototype.updatedAt = undefined;


