/*
 * My histories API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from '../ApiClient';
import {Profile} from './Profile';

/**
 * The Notification model module.
 * @module model/Notification
 * @version v1
 */
export class Notification {
  /**
   * Constructs a new <code>Notification</code>.
   * @alias module:model/Notification
   * @class
   * @param body {String} 
   * @param title {String} 
   */
  constructor(body, title) {
    this.body = body;
    this.title = title;
  }

  /**
   * Constructs a <code>Notification</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/Notification} obj Optional instance to populate.
   * @return {module:model/Notification} The populated <code>Notification</code> instance.
   */
  static constructFromObject(data, obj) {
    if (data) {
      obj = obj || new Notification();
      if (data.hasOwnProperty('pk'))
        obj.pk = ApiClient.convertToType(data['pk'], 'Number');
      if (data.hasOwnProperty('author'))
        obj.author = Profile.constructFromObject(data['author']);
      if (data.hasOwnProperty('body'))
        obj.body = ApiClient.convertToType(data['body'], 'String');
      if (data.hasOwnProperty('title'))
        obj.title = ApiClient.convertToType(data['title'], 'String');
      if (data.hasOwnProperty('status'))
        obj.status = ApiClient.convertToType(data['status'], 'String');
      if (data.hasOwnProperty('createdAt'))
        obj.createdAt = ApiClient.convertToType(data['createdAt'], 'String');
      if (data.hasOwnProperty('updatedAt'))
        obj.updatedAt = ApiClient.convertToType(data['updatedAt'], 'String');
      if (data.hasOwnProperty('receiver'))
        obj.receiver = Profile.constructFromObject(data['receiver']);
    }
    return obj;
  }
}

/**
 * @member {Number} pk
 */
Notification.prototype.pk = undefined;

/**
 * @member {module:model/Profile} author
 */
Notification.prototype.author = undefined;

/**
 * @member {String} body
 */
Notification.prototype.body = undefined;

/**
 * @member {String} title
 */
Notification.prototype.title = undefined;

/**
 * Allowed values for the <code>status</code> property.
 * @enum {String}
 * @readonly
 */
Notification.StatusEnum = {
  /**
   * value: "opened"
   * @const
   */
  opened: "opened",

  /**
   * value: "send"
   * @const
   */
  send: "send",

  /**
   * value: "received"
   * @const
   */
  received: "received",

  /**
   * value: "viewed"
   * @const
   */
  viewed: "viewed",

  /**
   * value: "closed"
   * @const
   */
  closed: "closed"
};

/**
 * @member {module:model/Notification.StatusEnum} status
 */
Notification.prototype.status = undefined;

/**
 * @member {String} createdAt
 */
Notification.prototype.createdAt = undefined;

/**
 * @member {String} updatedAt
 */
Notification.prototype.updatedAt = undefined;

/**
 * @member {module:model/Profile} receiver
 */
Notification.prototype.receiver = undefined;


