/*
 * Snippets API
 * Test description
 *
 * OpenAPI spec version: v1
 * Contact: contact@snippets.local
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.13
 *
 * Do not edit the class manually.
 *
 */

import {ApiClient} from './ApiClient';
import {Comment} from './model/Comment';
import {History} from './model/History';
import {InlineResponse200} from './model/InlineResponse200';
import {InlineResponse2001} from './model/InlineResponse2001';
import {InlineResponse2002} from './model/InlineResponse2002';
import {Profile} from './model/Profile';
import {Tag} from './model/Tag';
import {TokenObtainPair} from './model/TokenObtainPair';
import {TokenRefresh} from './model/TokenRefresh';
import {User} from './model/User';
import {AuthApi} from './api/AuthApi';
import {HistoriesApi} from './api/HistoriesApi';
import {ProfilesApi} from './api/ProfilesApi';
import {TagsApi} from './api/TagsApi';
import {UsersApi} from './api/UsersApi';


/**
* Test_description.<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var SnippetsApi = require('index'); // See note below*.
* var xxxSvc = new SnippetsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new SnippetsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new SnippetsApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new SnippetsApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version v1
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The Comment model constructor.
     * @property {module:model/Comment}
     */
    Comment,

    /**
     * The History model constructor.
     * @property {module:model/History}
     */
    History,

    /**
     * The InlineResponse200 model constructor.
     * @property {module:model/InlineResponse200}
     */
    InlineResponse200,

    /**
     * The InlineResponse2001 model constructor.
     * @property {module:model/InlineResponse2001}
     */
    InlineResponse2001,

    /**
     * The InlineResponse2002 model constructor.
     * @property {module:model/InlineResponse2002}
     */
    InlineResponse2002,

    /**
     * The Profile model constructor.
     * @property {module:model/Profile}
     */
    Profile,

    /**
     * The Tag model constructor.
     * @property {module:model/Tag}
     */
    Tag,

    /**
     * The TokenObtainPair model constructor.
     * @property {module:model/TokenObtainPair}
     */
    TokenObtainPair,

    /**
     * The TokenRefresh model constructor.
     * @property {module:model/TokenRefresh}
     */
    TokenRefresh,

    /**
     * The User model constructor.
     * @property {module:model/User}
     */
    User,

    /**
    * The AuthApi service constructor.
    * @property {module:api/AuthApi}
    */
    AuthApi,

    /**
    * The HistoriesApi service constructor.
    * @property {module:api/HistoriesApi}
    */
    HistoriesApi,

    /**
    * The ProfilesApi service constructor.
    * @property {module:api/ProfilesApi}
    */
    ProfilesApi,

    /**
    * The TagsApi service constructor.
    * @property {module:api/TagsApi}
    */
    TagsApi,

    /**
    * The UsersApi service constructor.
    * @property {module:api/UsersApi}
    */
    UsersApi
};
